### ISSUE TITLE
database.sql Import Error

### ISSUE THREAD

**Issue by tzt345** [Jecket22/GDOpenServer#10]
Please Help :(((

**Comment by Wyliemaster** [comment]
Did you select the database before trying to import?

**Comment by tzt345** [comment]
> Did you select the database before trying to import?

Yes!

**Comment by Jecket22** [comment]
Could you screenshot the error?

**Comment by tzt345** [comment]
> Could you screenshot the error?

Ok

**Comment by tzt345** [comment]
> Could you screenshot the error?

Here & there's more bugs in the database.sql :((((
![Screenshot_2021-05-17-20-21-36-82](https://user-images.githubusercontent.com/83703996/118487781-a4ca0580-b74d-11eb-8770-150126fbb611.png)

**Comment by tzt345** [comment]
There's more bugs in the database.sql file

**Comment by tzt345** [comment]
Can you fix it?

**Comment by Jecket22** [comment]
I'll have to look later into this, might be a minimal issue, though I cannot promise to look it up by today

**Comment by tzt345** [comment]
& I cannot login to my account :((

**Comment by Intelligent-Cat** [comment]
the latest commit should fix it

**Comment by tzt345** [comment]
> the latest commit should fix it

Ok 👌

**Comment by tzt345** [comment]
@Intelligent-Cat It doesn't work
![Uploading Screenshot_2021-05-22-21-06-13-64.png…]()

**Comment by tzt345** [comment]
@Intelligent-Cat It doesn't work
![Screenshot_2021-05-22-21-06-13-64](https://user-images.githubusercontent.com/83703996/119227705-d40fb680-bb41-11eb-813e-6d5fb1a4ee27.png)

**Comment by tzt345** [comment]
@Intelligent-Cat 
![Screenshot_2021-05-28-22-21-23-88](https://user-images.githubusercontent.com/83703996/119998284-24d05500-c003-11eb-9463-4a0c7e394618.png)
