### ISSUE TITLE
I have?

### ISSUE THREAD

**Issue by fancythedeveloper** [Jecket22/GDOpenServer#3]
While #2 is fixed, I have a new one now, with the latest commit.

When I try to feature/epic/magic a level, it will give me the message "This level already has (thing) here." Even though I only star-rated it.

**Comment by fancythedeveloper** [comment]
To add to that, when I try to make a Map Pack, it always says `Invalid color given` or something.

**Comment by fancythedeveloper** [comment]
To extend my issue, some commands, like !rename, just gives me Comment upload failed, but it doesn't work.

BTW, all of this running of a Google Cloud VPS.

**Comment by Intelligent-Cat** [comment]
could we have the errors in our hands

**Comment by Intelligent-Cat** [comment]
And a list of all commands that give command upload failed and their sent errors?

**Comment by fancythedeveloper** [comment]
Errors? Uh... how would I check for that?

**Comment by Intelligent-Cat** [comment]
wireshark

**Comment by Intelligent-Cat** [comment]
can we at least have the link to the gdps

**Comment by fancythedeveloper** [comment]
Sure, http://fancygmdps.tk/database

**Comment by Intelligent-Cat** [comment]
check the new commit and try doing the things that did not work previously

**Comment by Intelligent-Cat** [comment]
ok can we close this now

**Comment by Jecket22** [comment]
ig
