### ISSUE TITLE
Importing database.sql causes "no database selected" error (7m.pl)

### ISSUE THREAD

**Issue by NoahGMD** [Jecket22/GDOpenServer#5]
![Screenshot_20201214-084545.png](https://user-images.githubusercontent.com/73782137/102088353-c878d080-3de8-11eb-9c2c-071b348273a9.png)

**Comment by Jecket22** [comment]
You probably forgot to select the database, or atleast forgot to click on it. Once you did that you can import the sql file. _Note again though, most stuff are still wip and doesn't work 100%, especially commands so far._

**Comment by Wyliemaster** [comment]
Iirc, 7m.pl also forces you to wait about 10 minutes before you can import a database since they're still setting things up, that could also be the reason its not working

**Comment by fancythedeveloper** [comment]
> Iirc, 7m.pl also forces you to wait about 10 minutes before you can import a database since they're still setting things up, that could also be the reason its not working

Don't remember that happening.

**Comment by Intelligent-Cat** [comment]
will close due to it being yourself, not us
